#ifndef _DEFINES_HPP_
#define _DEFINES_HPP_

#define VECTOR_BLOCK_BYTES sizeof(unsigned int)
#define VECTOR_BLOCK_BITS (int)(VECTOR_BLOCK_BYTES * 8)

#define TREE_DEGREE_EXP 2
#define TREE_DEGREE ((unsigned int)1 << TREE_DEGREE_EXP)
#define DEFAULT_TREE_SHIFT (VECTOR_BLOCK_BITS - TREE_DEGREE_EXP)
#define DEFAULT_MASK ((TREE_DEGREE - 1) << DEFAULT_TREE_SHIFT)
#define LAYERS_IN_BLOCK (VECTOR_BLOCK_BITS / TREE_DEGREE_EXP)
#define STARTING_BIT_MASK (unsigned int)(1 << (VECTOR_BLOCK_BITS - 1))
#define MAX_THREAD_COUNT 512

#define RANDOM_SEED 2137

#endif